### ISSUE TITLE
Invalid auth

### ISSUE THREAD

**Issue by Stvad** [sebseager/slack-exporter#1]
Hi! I'm trying to use this. I've set the token (tried both .env and the env variable directly), but I'm getting the following error:

```bash
> python3 exporter.py --lu
I encountered an error: {'ok': False, 'error': 'invalid_auth'}
```

**Comment by EdgeToLife** [comment]
same

**Comment by EdgeToLife** [comment]
> Hi! I'm trying to use this. I've set the token (tried both .env and the env variable directly), but I'm getting the following error:
> 
> ```shell
> > python3 exporter.py --lu
> I encountered an error: {'ok': False, 'error': 'invalid_auth'}
> ```

same

**Comment by sebseager** [comment]
Looks like the Slack API has changed, and OAuth2.0 tokens now need to be passed in the request header, not via the `token` param. Slack docs aren't very helpful, but this should be an easy fix.

**Comment by sebseager** [comment]
This should be fixed as of https://github.com/sebseager/slack-exporter/commit/a67bed98b1e0b98fc6ba1458a9021229b2e5b9f2
